"""Report generation — terminal and markdown output."""
from __future__ import annotations
from datetime import datetime

from .analyzer import RiskReport, RiskFactor, grade_color
from .protocols import Protocol


def format_markdown(report: RiskReport) -> str:
    """Generate a markdown risk report."""
    lines = [
        "# DeFi Risk Scanner — Protocol Risk Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "---",
        "",
        f"## {report.protocol.name}",
        "",
        f"- **Category:** {report.protocol.category}",
        f"- **Chain:** {report.protocol.chain}",
        f"- **Main Contract:** `{report.protocol.main_contract}`",
        f"- **Website:** {report.protocol.website}",
        f"- **Deployed:** {report.protocol.deployed_date or 'Unknown'}",
        f"- **Audits:** {', '.join(report.protocol.audits) if report.protocol.audits else 'None known'}",
        "",
        f"### Overall Risk Score: {report.overall_grade} ({report.overall_score:.1f}/100)",
        "",
    ]

    # Grade scale
    lines.append("| Grade | Score Range | Meaning |")
    lines.append("|-------|-----------|---------|")
    lines.append("| A | 0-15 | Low risk |")
    lines.append("| B | 16-30 | Moderate risk |")
    lines.append("| C | 31-50 | Elevated risk |")
    lines.append("| D | 51-70 | High risk |")
    lines.append("| E | 71-85 | Very high risk |")
    lines.append("| F | 86-100 | Critical risk |")
    lines.append("")

    # Risk factors
    lines.append("---")
    lines.append("")
    lines.append("## Risk Factors")
    lines.append("")

    for f in report.factors:
        lines.append(f"### {f.name} — Grade {f.grade} ({f.score:.0f}/100)")
        lines.append(f"**Weight:** {f.weight*100:.0f}%")
        lines.append("")
        lines.append(f"**Analysis:** {f.details}")
        lines.append("")
        lines.append(f"**Recommendation:** {f.recommendation}")
        lines.append("")

    # Summary
    lines.append("---")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"**{report.protocol.name}** receives an overall risk grade of **{report.overall_grade}** "
                 f"(score: {report.overall_score:.1f}/100).")
    lines.append("")

    high_risk = [f for f in report.factors if f.score >= 50]
    if high_risk:
        lines.append("**Key concerns:**")
        for f in high_risk:
            lines.append(f"- {f.name}: {f.details}")
        lines.append("")

    low_risk = [f for f in report.factors if f.score <= 20]
    if low_risk:
        lines.append("**Strengths:**")
        for f in low_risk:
            lines.append(f"- {f.name}: {f.details}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by DeFi Risk Scanner — AI-powered DeFi risk analysis*")
    return "\n".join(lines)


def print_terminal(report: RiskReport) -> None:
    """Print a formatted terminal report."""
    print("=" * 60)
    print("  DeFi Risk Scanner — Protocol Risk Report")
    print("=" * 60)
    print(f"  Protocol:  {report.protocol.name}")
    print(f"  Category:  {report.protocol.category}")
    print(f"  Chain:     {report.protocol.chain}")
    print(f"  Contract:  {report.protocol.main_contract}")
    print(f"  Website:   {report.protocol.website}")
    print(f"  Deployed:  {report.protocol.deployed_date or 'Unknown'}")
    print(f"  Audits:    {', '.join(report.protocol.audits) if report.protocol.audits else 'None'}")
    tvl = report.tvl_data.get('current_tvl', 0)
    print(f"  TVL:       ${tvl:,.0f}" if tvl else "  TVL:       N/A")
    print()
    print(f"  OVERALL:   {report.overall_grade} (score: {report.overall_score:.1f}/100)")
    print("=" * 60)
    print()

    grade_scale = {
        "A": "Low risk", "B": "Moderate risk", "C": "Elevated risk",
        "D": "High risk", "E": "Very high risk", "F": "Critical risk",
    }
    print(f"  A=Low | B=Moderate | C=Elevated | D=High | E=Very High | F=Critical")
    print()

    for f in report.factors:
        icon = "[!!!]" if f.score >= 50 else "[!]" if f.score >= 30 else "[ok]"
        print(f"  {icon} {f.name:25s}  Grade {f.grade}  ({f.score:.0f}/100)  Weight {f.weight*100:.0f}%")
        print(f"      {f.details}")
        print(f"      -> {f.recommendation}")
        print()

    # Exploit warning
    if report.protocol.exploits:
        print("-" * 60)
        print("  [!!!] EXPLOIT HISTORY:")
        for exploit in report.protocol.exploits:
            print(f"    - {exploit}")
        print()

    print("-" * 60)
    print(f"  FINAL: {report.protocol.name} = {report.overall_grade} ({report.overall_score:.1f}/100)")
    high = [f for f in report.factors if f.score >= 50]
    if high:
        print(f"  WARNING: {len(high)} high-risk factor(s) detected")
    print("-" * 60)
